# Generated by Django 2.0.6 on 2019-06-05 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('key', '0002_auto_20190605_1705'),
        ('product', '0001_initial'),
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='key.Key'),
        ),
        migrations.AddField(
            model_name='company',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='product.Product'),
        ),
    ]
