# Generated by Django 2.0.6 on 2019-06-05 21:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('client', '0002_auto_20190605_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
