# Generated by Django 2.2.3 on 2019-07-20 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('key', '0010_auto_20190720_1418'),
        ('client', '0004_company_company_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='key',
        ),
        migrations.AddField(
            model_name='company',
            name='keys',
            field=models.ManyToManyField(related_name='keys', related_query_name='company_key', to='key.Key'),
        ),
    ]
