# Generated by Django 2.2.3 on 2019-07-24 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_company_keys'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='company_logo',
            new_name='logo',
        ),
    ]
