# Generated by Django 2.2.3 on 2019-07-23 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20190605_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='limit_register',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('SVR', 'Server'), ('CLI', 'Client'), ('MOB', 'Mobile'), ('WEB', 'Web')], default='CLI', max_length=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
