# Generated by Django 2.2.3 on 2019-07-23 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('key', '0015_auto_20190723_1310'),
        ('product', '0003_auto_20190723_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='keys',
            field=models.ManyToManyField(related_name='keys', related_query_name='company_key', to='key.Key'),
        ),
    ]
