# Generated by Django 2.2.3 on 2019-07-23 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_keys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='keys',
            field=models.ManyToManyField(to='key.Key'),
        ),
    ]
