# Generated by Django 2.2.3 on 2019-07-24 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20190723_2024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='keys',
        ),
    ]
