# Generated by Django 2.0.6 on 2019-06-05 19:45

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Key',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=20)),
                ('valid_date', models.DateTimeField(default=datetime.datetime(2019, 7, 5, 16, 45, 32, 323028))),
            ],
        ),
    ]
