# Generated by Django 2.0.6 on 2019-06-05 20:05

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('key', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='valid_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 5, 17, 5, 4, 763849)),
        ),
    ]
