# Generated by Django 2.0.6 on 2019-06-05 20:19

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('key', '0002_auto_20190605_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='key',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='key',
            name='valid_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 5, 17, 19, 28, 825901)),
        ),
    ]
