# Generated by Django 2.0.6 on 2019-06-05 22:49

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('key', '0005_auto_20190605_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='valid_date',
            field=models.DateField(default=datetime.datetime(2019, 7, 5, 19, 49, 0, 178629)),
        ),
    ]
