# Generated by Django 2.2.3 on 2019-07-19 01:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('key', '0006_auto_20190605_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='key',
            name='machine',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='key',
            name='valid_date',
            field=models.DateField(default=datetime.datetime(2020, 7, 17, 22, 15, 56, 46533)),
        ),
    ]
