# Generated by Django 2.2.3 on 2019-07-19 01:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('key', '0007_auto_20190718_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='key',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='key',
            name='valid_date',
            field=models.DateField(default=datetime.datetime(2020, 7, 17, 22, 16, 40, 155365)),
        ),
    ]
