# Generated by Django 2.2.3 on 2019-07-20 16:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('key', '0008_auto_20190718_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='valid_date',
            field=models.DateField(default=datetime.datetime(2020, 7, 19, 13, 58, 58, 52004)),
        ),
    ]
