# Generated by Django 2.2.3 on 2019-07-20 17:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('key', '0009_auto_20190720_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='valid_date',
            field=models.DateField(default=datetime.datetime(2020, 7, 19, 14, 18, 45, 960180)),
        ),
    ]
