# Generated by Django 2.2.3 on 2019-07-23 16:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('key', '0014_auto_20190723_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='valid_date',
            field=models.DateField(default=datetime.datetime(2020, 7, 22, 13, 10, 44, 792478)),
        ),
    ]
